### ISSUE TITLE
配置变量里seekbarfg_color疑似RGB写反，写成了BGR

### ISSUE THREAD

**Issue by Qing-JiuJiu** [FinnRaze/mpv-osc-modern-f#10]
当颜色代码设置：seekbarfg_color = "a8a1f0"
实际生效的颜色代码为：f0a1a8
![image](https://github.com/user-attachments/assets/c07d8781-3205-4512-a090-7cf75f64d3b9)

**Comment by verygoodlee** [comment]
因为OSC的本质就是高级字幕，按照ass字幕的标准，颜色就是用bgr表示的。

官方默认OSC最近也添加了自定义颜色支持，但是他做了rgb->bgr转换，用户只要配置rgb
https://github.com/mpv-player/mpv/blob/fe4ba71962bd69e1c3bc56bd16b3b58b0db12268/player/lua/osc.lua#L104-L106

**Comment by FinnRaze** [comment]
有段时间没看github了，有其他人提出PR，已合并https://github.com/FinnRaze/mpv-osc-modern-f/pull/12
