### ISSUE TITLE
Mouse hovering fix

### ISSUE THREAD

**Issue by da3dsoul1** [FinnRaze/mpv-osc-modern-f#2]
When bottom hovering without moving the mouse osc keeps disappearing, can this behavior get fixed? Osc should be visible when mouse is in that zone!

https://github.com/FinnRaze/mpv-osc-modern-f/assets/111184581/a6ab184a-b44e-450e-96cf-745d6518890e

**Comment by da3dsoul1** [comment]
There's also a problem where hovering mouse to the top right corner makes osc appear

https://github.com/FinnRaze/mpv-osc-modern-f/assets/111184581/46b492dc-06ad-41da-a504-1b41eb4c349c


Is it possible to fix these issues?

**Comment by FinnRaze** [comment]
It's about "deadzone" in [osc](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua). long as I get free time and accessbility to github,I'll consider to fix

**Comment by da3dsoul1** [comment]
Got it, thank you for your work if you will continue the project

**Comment by FinnRaze** [comment]
Decided to keep the same behavior with osc : only keep visible in "input area" (rectangular area where contains interactive buttons/bars) .There is going to have a "deadzone" option in next commit

**Comment by techz1** [comment]
不确定是否同一个问题：以窗口模式播放时，鼠标从左上角进入画面 UI 不显示，从右上角进入 UI 会出现后会马上消失，只有鼠标从下方进入画面会 UI 才会正常出现

**Comment by FinnRaze** [comment]
> 不确定是否同一个问题：以窗口模式播放时，鼠标从左上角进入画面 UI 不显示，从右上角进入 UI 会出现后会马上消失，只有鼠标从下方进入画面会 UI 才会正常出现

右上角和下方均有触发区，且必须停留在渲染的元素上OSC才会持续显示，否则按fadeduration时长暂时显示。假如你在mpv使用--no-border，此时OSC会在右上角渲染三个图标，鼠标停留在图标区亦可持续显示

**Comment by techz1** [comment]
明白了，感谢回复。全屏状态下这么用倒是挺方便的。

**Comment by verygoodlee** [comment]
> 右上角和下方均有触发区，且必须停留在渲染的元素上OSC才会持续显示，否则按fadeduration时长暂时显示。假如你在mpv使用--no-border，此时OSC会在右上角渲染三个图标，鼠标停留在图标区亦可持续显示

@FinnRaze 或许这样写更好，如果窗口有边框，右上角图标是不渲染的，同时也不应该添加这个触发区，\
利用现有的`window_controls_enabled()`判断一下图标是否渲染即可
```lua
if window_controls_enabled() then
    add_area('showhide_wc', osc_param.playresx*0.5, 0, osc_param.playresx, 48)
end
```
