### ISSUE TITLE
暂停时有点bug，附带解决方法

### ISSUE THREAD

**Issue by verygoodlee** [FinnRaze/mpv-osc-modern-f#3]
1. `showonpause=yes`开启后，暂停时OSC一直显示，这没啥问题
- 点击开始按钮时，OSC会自动消失，消失后鼠标略微移动一下，OSC又重新出现了，行为非常奇怪，\
我觉得点击开始时鼠标很明显在触发区域内，OSC不应该消失的

关于这一点我暂时改了`always_on()`函数，把关闭的逻辑去掉了，这里强制关闭有点多余，会自动根据鼠标位置判断是否关闭的
```lua
function always_on(val)
    if state.enabled then
        if val then
            show_osc()
        end
    end
end
```

2. 不论`showonpause`是否开启，暂停状态时
- 把鼠标移到置顶按钮单击，实际置顶状态是切换了的，但是按钮没切换，即OSC状态没刷新，鼠标略微移动一下触发刷新才正常
- 音量显示也有同样的问题，鼠标移动到最下方，用快捷键加减音量或者静音，音量显示没变化，需要移动一下鼠标触发刷新

这个问题应该要改下 `mp.observe_property('volume', ...)` `mp.observe_property('mute', ...)`这些监控属性变化的函数吧，另外还需要加个置顶属性的监控`mp.observe_property('ontop', ...)`，里面都调用一下`request_tick()`刷新OSC
```lua
mp.observe_property('mute', 'bool',
    function(name, val)
        state.mute = val
        request_tick()
    end
)
mp.observe_property('volume', 'number',
    function(name, val)
        state.sys_volume = val
        if user_opts.processvolume then
            state.proc_volume = val*val/100
        else
            state.proc_volume = val
        end
        request_tick()
    end
)
mp.observe_property('ontop', nil, request_tick)
```

**Comment by FinnRaze** [comment]
多谢指教，已更新
