### ISSUE TITLE
求添加一个字幕/音频轨道的选择

### ISSUE THREAD

**Issue by wzdc** [FinnRaze/mpv-osc-modern-f#6]
点击字幕或音频按钮时显示一个框来让用户选择字幕和音频而不是切换字幕，就像这样
![image](https://github.com/FinnRaze/mpv-osc-modern-f/assets/53571020/c2c16b79-8e7c-4c80-beaa-464306805534)

**Comment by FinnRaze** [comment]
no plan,issue ignored

**Comment by FinnRaze** [comment]
no plan,issue ignored
